### ISSUE TITLE
Add Yandex Disk File Provider

### ISSUE THREAD

**Issue by worldbeater** [worldbeater/Camelotia#1]
Adding Yandex Disk file system provider will make the application useful for people who store their files on Yandex Disk. They should be able to easily upload, download, rename and delete files hosted on Yandex servers. 

**Implementation Details**

File browser could be implemented using [Refit](https://github.com/reactiveui/refit) library to generate REST API clients for [Yandex Disk API](https://tech.yandex.ru/disk/). A default .NET HTTPListener could be used to receive access code from [Yandex OAuth API](https://tech.yandex.com/oauth/).

**Task List**

- [x] Use HTTP Listener and OAuth protocol to authenticate users on Yandex
- [x] Create file browser using Yandex REST API
- [x] Implement Download functionality
- [x] Implement Upload functionality
