### ISSUE TITLE
Use Akavache to store auth tokens locally

### ISSUE THREAD

**Issue by worldbeater** [worldbeater/Camelotia#4]
Storing tokens locally will definitely improve the UX. 

**Implementation Details**

We could use [Akavache](https://github.com/reactiveui/Akavache) to implement this feature. [Akavache](https://github.com/reactiveui/Akavache) is an asynchronous, persistent key-value store that works on all platforms, including Windows, Android, iOS, Linux, OSX (without any need to take care of creating database files, choosing secure paths to store tokens, etc. really a great library)

**Task List**

- [x] Add Akavache package to `Camelotia.Services` project
- [x] Create an `IStringCache` interface with `Write` and `Read` methods
- [x] Create `AkavacheStringCache` class that implements `IStringCache`
- [x] Write integrational tests for the cache
- [x] Inject the cache into file providers and reuse
